-- Active: 1698415370372@@127.0.0.1@8889

CREATE DATABASE RECETTES;


USE RECETTES;

CREATE TABLE `RECIP_CATEGORIES`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `RECIPS_id` INT NULL,
    `CATEGORIES_id` INT NULL
);
ALTER TABLE
    `RECIP_CATEGORIES` ADD INDEX `recip_categories_recips_id_index`(`RECIPS_id`);
ALTER TABLE
    `RECIP_CATEGORIES` ADD INDEX `recip_categories_categories_id_index`(`CATEGORIES_id`);
CREATE TABLE `ADMINS`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `VALUE` TINYINT(1) NULL
);
CREATE TABLE `TYPES_INGREDIENT`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NULL
);
CREATE TABLE `INSTRUCTIONS`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `TEXT` VARCHAR(255) NULL
);
CREATE TABLE `STEPS`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE `PICTURES`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `URL` VARCHAR(255) NULL,
    `LEGEND` VARCHAR(255) NOT NULL
);
CREATE TABLE `CATEGORIES`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NULL,
    `RECIP_INGREDIENTS_id` INT NULL
);
ALTER TABLE
    `CATEGORIES` ADD INDEX `categories_recip_ingredients_id_index`(`RECIP_INGREDIENTS_id`);

ALTER TABLE `CATEGORIES`
CHANGE COLUMN `RECIP_INGREDIENTS_id RECIP_CATEGORIES_id INT`;

CREATE TABLE `INGREDIENTS`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(255) NULL,
    `CALORIES` DECIMAL(8, 2) NOT NULL,
    `QUANTITIES` VARCHAR(255) NULL,
    `RECIP_INGREDIENTS_id` INT NULL
);
ALTER TABLE
    `INGREDIENTS` ADD INDEX `ingredients_recip_ingredients_id_index`(`RECIP_INGREDIENTS_id`);
CREATE TABLE `COMMENTAIRES`(
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `TEXT` TEXT NULL,
    `DATE` DATE NULL,
    `TIME` DATETIME NULL,
    `NOTE_COM` DOUBLE NULL
);
CREATE TABLE `RECIP_INGREDIENTS`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `RECIPS_id` INT NULL,
    `INGREDIENTS_id` INT NULL
);
ALTER TABLE
    `RECIP_INGREDIENTS` ADD INDEX `recip_ingredients_recips_id_index`(`RECIPS_id`);
ALTER TABLE
    `RECIP_INGREDIENTS` ADD INDEX `recip_ingredients_ingredients_id_index`(`INGREDIENTS_id`);
CREATE TABLE `LEVELS`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `VALUE` VARCHAR(255) NULL
);
CREATE TABLE `USERS`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `USERNAME` VARCHAR(255) NULL,
    `PASSWORD` VARCHAR(255) NULL,
    `MAIL_ADRESS` VARCHAR(255) NULL,
    `ROLE` VARCHAR(255) NULL
);
CREATE TABLE `RECIPS`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `TITLE` VARCHAR(255) NULL,
    `DESCRIPTION` VARCHAR(255) NULL,
    `TIME` TIME NOT NULL,
    `NOTE_RECIP` DOUBLE NULL,
    `RECIP_INGREDIENTS_id` INT NULL,
    `RECIP_CATEGORIES_id` INT NULL
);
ALTER TABLE
    `RECIPS` ADD INDEX `recips_recip_categories_id_index`(`RECIP_CATEGORIES_id`);
ALTER TABLE
    `RECIPS` ADD INDEX `recips_recip_ingredients_id_index`(`RECIP_INGREDIENTS_id`);
ALTER TABLE
    `RECIPS` ADD CONSTRAINT `recips_id_foreign` FOREIGN KEY(`id`) REFERENCES `PICTURES`(`id`);
ALTER TABLE
    `RECIP_CATEGORIES` ADD CONSTRAINT `recip_categories_categories_id_foreign` FOREIGN KEY(`CATEGORIES_id`) REFERENCES `CATEGORIES`(`id`);
ALTER TABLE
    `ADMINS` ADD CONSTRAINT `admins_id_foreign` FOREIGN KEY(`id`) REFERENCES `RECIPS`(`id`);
ALTER TABLE
    `USERS` ADD CONSTRAINT `users_id_foreign` FOREIGN KEY(`id`) REFERENCES `ADMINS`(`id`);
ALTER TABLE
    `INGREDIENTS` ADD CONSTRAINT `ingredients_recip_ingredients_id_foreign` FOREIGN KEY(`RECIP_INGREDIENTS_id`) REFERENCES `RECIP_INGREDIENTS`(`INGREDIENTS_id`);
ALTER TABLE
    `COMMENTAIRES` ADD CONSTRAINT `commentaires_id_foreign` FOREIGN KEY(`id`) REFERENCES `RECIPS`(`id`);
ALTER TABLE
    `RECIPS` ADD CONSTRAINT `recips_recip_ingredients_id_foreign` FOREIGN KEY(`RECIP_INGREDIENTS_id`) REFERENCES `RECIP_INGREDIENTS`(`RECIPS_id`);
ALTER TABLE
    `RECIPS` ADD CONSTRAINT `recips_id_foreign` FOREIGN KEY(`id`) REFERENCES `LEVELS`(`id`);
ALTER TABLE
    `RECIPS` ADD CONSTRAINT `recips_id_foreign` FOREIGN KEY(`id`) REFERENCES `STEPS`(`id`);
ALTER TABLE
    `RECIPS` ADD CONSTRAINT `recips_recip_categories_id_foreign` FOREIGN KEY(`RECIP_CATEGORIES_id`) REFERENCES `RECIP_CATEGORIES`(`RECIPS_id`);
ALTER TABLE
    `TYPES_INGREDIENT` ADD CONSTRAINT `types_ingredient_id_foreign` FOREIGN KEY(`id`) REFERENCES `INGREDIENTS`(`id`);
ALTER TABLE
    `COMMENTAIRES` ADD CONSTRAINT `commentaires_id_foreign` FOREIGN KEY(`id`) REFERENCES `USERS`(`id`);
ALTER TABLE
    `INSTRUCTIONS` ADD CONSTRAINT `instructions_id_foreign` FOREIGN KEY(`id`) REFERENCES `STEPS`(`id`);

ALTER TABLE `USERS`
MODIFY `ROLE` VARCHAR(255) NOT NULL DEFAULT 'USER';

ALTER TABLE `RECIPS`
ADD `NOTE_COUNT` INT NOT NULL DEFAULT 0,
ADD `NOTE_TOTAL` DOUBLE NOT NULL DEFAULT 0;

ALTER TABLE `RECIPS` DROP COLUMN `NOTE_RECIP`;

ALTER TABLE `RECIPS`
ADD `NOTE_RECIP` DOUBLE NOT NULL DEFAULT 0;


UPDATE `RECIPS`
SET `NOTE_RECIP` = `NOTE_TOTAL` / `NOTE_COUNT`
WHERE `NOTE_COUNT` > 0;